version: "3.8"

networks:
  minha-rede:

services:
  discovery:
    build:
      context: ./discovery
    ports:
      - "8761:8761"
    networks:
      - minha-rede

  usuario-service:
    build:
      context: ./usuario-service
    depends_on:
      - discovery
    networks:
      - minha-rede

  gateway:
    build:
      context: ./gateway
    ports:
      - "8084:8084"
    depends_on:
      - discovery
    networks:
      - minha-rede