version: "3.8"

networks:
  my-network:

services:
  discovery:
    build:
      context: ./discovery
    ports:
      - "8761:8761"
    networks:
      - my-network

  gateway:
    build:
      context: ./gateway
    ports:
      - "8084:8084"
    depends_on:
      - discovery
    networks:
      - my-network

  property:
    build:
      context: ./property
    depends_on:
      - discovery
    networks:
      - my-network

  user:
    build:
      context: ./usuario-service
    depends_on:
      - discovery
    networks:
      - my-network

