server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: property
          uri: lb://property
          predicates:
            - Path=/property/**