server:
  port: 8084
# descomentar linhas abaixo para o docker compose
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/**