server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**,/auth/**
            # - Path=/auth/**
            # - Path=/login/google
            # - Path=/signin-google
        - id: property
          uri: lb://property
          predicates:
            - Path=/property/**,/reservation/**,/review/**
            # - Path=/auth/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/transaction/**
