spring:
  application:
    name: payment
  datasource:
    url: jdbc:h2:mem:testDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true

server:
  port: 8082
  forward-headers-strategy: framework
  error:
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/